version: '2'
services:
  book-service:
    image:
      book-store-service
    ports:
      - "8080:8080"
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: icebreakers
      POSTGRES_PASSWORD: anonymous
      POSTGRES_DB: bookdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: